wordpress:
  image: wordpress
  links:
    - db:mysql
  ports:
    - 8080:80
  volumes:
    - site:/var/www/html/wp-content/plugins/site

db:
  image: mariadb
  environment:
    MYSQL_ROOT_PASSWORD: example
